name: Deploy FastAPI to Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - name: Configure Docker for Google Cloud
      run: gcloud auth configure-docker

    - name: Build and push Docker image
      run: |
        docker buildx build --push --platform linux/amd64 -t gcr.io/$PROJECT_ID/fastapi-app:$GITHUB_SHA .
      env:
        PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy fastapi-app \
          --image gcr.io/$PROJECT_ID/fastapi-app:$GITHUB_SHA \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --port 8080
      env:
        PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
